### ISSUE TITLE
Feature request : Remux mkv to mp4 even for non-Dolby Vision video.

### ISSUE THREAD

**Issue by bluewidy** [nilaoda/DoViMuxer#1]
I am a user who wants to convert dolby atmos mkv to mp4. I know I can convert mkv to mp4 very easily via ffmpeg. However, it has a flaw: it does not present the complexity index of eac3-joc. However, this tool is representing it correctly.

**Comment by nilaoda** [comment]
The v1.0.0 version already supports non-Dolby Vision video import. (video track **MUST** be HEVC).

**Comment by bluewidy** [comment]
Thank you for the information. That's sad. Because mine is H264.

**Comment by sw5163** [comment]
> Thank you for the information. That's sad. Because mine is H264.

Try something like
`mp4box -add sdr.h264 -add atmos.eac3 -new test.mp4`
latest mp4box supports eac3 atmos.

**Comment by bluewidy** [comment]
Hey, I succeeded in remuxing mkv to mp4 in Latest nightly Build!
<img width="667" alt="It works!" src="https://user-images.githubusercontent.com/40682277/198841816-7d16dfd6-def2-4cbe-8fa3-1113d048e5d5.png">

Can you possibly replace mp4box.exe with Latest nightly Build?
<img width="777" alt="Latest nightly Build" src="https://user-images.githubusercontent.com/40682277/198841862-5770326f-0909-4e65-8e57-3ab812023003.png">

Because mp4box.exe provided by DoviMuxer does not support mkv to mp4 remux.
<img width="614" alt="DoViMuxer's mp4box" src="https://user-images.githubusercontent.com/40682277/198842119-d36e5d9b-cfbd-4836-bf08-cd224c8d3a9c.png">

**Comment by sw5163** [comment]
You can just use ffmpeg to extract video and audio in the first place
`ffmpeg -i video.mkv -map 0:0 -c copy sdr.h264 -map 0:1 -c copy atmos.eac3`
And then mux with mp4box
`mp4box -add sdr.h264 -add atmos.eac3 -new test.mp4`
It ensures you Apple compatible Atmos playback regarding the `Complexity ID` problem.

What you are trying to achieve here is not the main purpose of this tool, I believe.
Use the combination of ffmpeg and mp4box instead.

Oh and regarding the `Complexity ID`, if you want to properly restore it from a ‘not present’ file, make sure you are using newer mp4box
https://github.com/gpac/gpac/issues/2217#issuecomment-1238559672

**Comment by bluewidy** [comment]
No need to go through the process of extracting video and audio. Because this one sentence sets the complexity index correctly.

`mp4box -add target.mkv -new output.mp4`

So I don't need ffmpeg.

**Comment by sw5163** [comment]
> No need to go through the process of extracting video and audio. Because this one sentence sets the complexity index correctly.
> 
> `mp4box -add target.mkv -new output.mp4`
> 
> So I don't need ffmpeg.

Interesting, maybe they update the workflow since last time i check.
Will look into that, thanks.
