### ISSUE TITLE
mkv to mp4 remux for dolby vision profile 8 constructs incorrect metadata.

### ISSUE THREAD

**Issue by bluewidy** [nilaoda/DoViMuxer#6]
[MediaInfo.txt](https://github.com/nilaoda/DoViMuxer/files/10333783/MediaInfo.txt)

**Comment by nilaoda** [comment]
Send sample mkv plz.

**Comment by bluewidy** [comment]
https://file.kiwi/qzTzhXZR#dStMpyaMR-q74P9B4r1lVg

**Comment by nilaoda** [comment]
I couldn't download it. You can just split a little clip for me (use MKVToolNix).

**Comment by bluewidy** [comment]
[minisample.zip](https://github.com/nilaoda/DoViMuxer/files/10353534/minisample.zip)

**Comment by nilaoda** [comment]
This is caused by mp4muxer and I don't know why...

**Comment by bluewidy** [comment]
okay. Thank you for your review.

**Comment by bluewidy** [comment]
> This is caused by mp4muxer and I don't know why...

I have an idea I'd like to suggest. 
https://www.bento4.com/documentation/mp4mux/
How about using this instead of mp4muxer?

**Comment by nilaoda** [comment]
> > This is caused by mp4muxer and I don't know why...
> 
> I have an idea I'd like to suggest. https://www.bento4.com/documentation/mp4mux/ How about using this instead of mp4muxer?

I will consider it.

**Comment by nilaoda** [comment]
@bluewidy Try latest version

https://github.com/nilaoda/DoViMuxer/releases

**Comment by bluewidy** [comment]
Now this works great. Thank you!
